interface=wlan0
driver=nl80211

ssid=__SSID__
hw_mode=g
channel=1
bridge=br0

ieee80211n=1
ieee80211d=1
ht_capab=[HT20]
wmm_enabled=1
max_num_sta=10
ap_isolate=0

auth_algs=1
wpa=2
wpa_passphrase=__PASS__
wpa_key_mgmt=WPA-PSK
rsn_pairwise=CCMP
